### ISSUE TITLE
active_job/railtie (LoadError)

### ISSUE THREAD

**Issue by benjaminsehl** [sprangular/sprangular_static_content#4]
Hey — hopefully this isn't too stupid of a question. I've set up a new Sprangular app, and tried to install static content, I get the following error when running: `rails g spree_static_content:install`

```
$ rails g spree_static_content:install
/Users/whoisbenjamin/Dropbox/Kotn/spree/kotn-2-0/config/application.rb:5:in `require': cannot load such file -- active_job/railtie (LoadError)
    from /Users/whoisbenjamin/Dropbox/Kotn/spree/kotn-2-0/config/application.rb:5:in `<top (required)>'
    from /Users/whoisbenjamin/.rvm/gems/ruby-2.2.1/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:146:in 'require'
    from /Users/whoisbenjamin/.rvm/gems/ruby-2.2.1/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:146:in 'require_application_and_environment!'
    from /Users/whoisbenjamin/.rvm/gems/ruby-2.2.1/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:133:in `generate_or_destroy'
    from /Users/whoisbenjamin/.rvm/gems/ruby-2.2.1/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:51:in `generate'
    from /Users/whoisbenjamin/.rvm/gems/ruby-2.2.1/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/whoisbenjamin/.rvm/gems/ruby-2.2.1/gems/railties-4.1.8/lib/rails/commands.rb:17:in '<top (required)>'
    from bin/rails:4:in 'require'
    from bin/rails:4:in '<main>'
```

**Comment by joshnuss** [comment]
Hey @bsehl,

Looks like your rails app was created with rails 4.2, but sprangular depends on rails 4.1.x ATM

**Comment by benjaminsehl** [comment]
Ah — thanks @joshnuss, yeah, derp! Did that originally, and then only changed rails version in the Gemfile. Thx!
